### ISSUE TITLE
Causes error in st.status

### ISSUE THREAD

**Issue by mkleinbort-ic** [joy13975/streamlit-nested-layout#3]
This code fails:

```python
import time
import streamlit as st
import streamlit_nested_layout

with st.status("Downloading data..."):
    st.write("Searching for data...")
    time.sleep(2)
    st.write("Found URL.")
    time.sleep(1)
    st.write("Downloading data...")
    time.sleep(1)
```

With error:

`TypeError: _nestable_block() got an unexpected keyword argument 'dg_type'`

The code works if one removes streamlit_nested_layout

**Comment by joy13975** [comment]
@mkleinbort-ic what is the version of Python & Streamlit that you are using?

**Comment by mkleinbort-ic** [comment]
Python 3.10.9, Streamlit 1.32.2

**Comment by joy13975** [comment]
@mkleinbort-ic just pushed an update to adapt the code to streamlit `1.32.2`.
New demo results in README. Can you do `pip install -U streamlit-nested-layout` and check again?

**Comment by mkleinbort-ic** [comment]
@joy13975 Seems to be fixed - will let you know if I hit issues. 
Also... regarding the speed of this fix: https://youtu.be/QWEcMqM0acU

**Comment by joy13975** [comment]
Glad to hear.
It’s also a complete coincidence that I happen to have a few minutes for this 😉
